# Generated by Django 4.1.5 on 2023-01-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('radio', 'радиобаттоны'), ('checkbox', 'чекбоксы'), ('text', 'текстовый')], default='radio', max_length=50, verbose_name='Текст ответа')),
                ('question', models.CharField(max_length=255, verbose_name='текст вопроса задания')),
                ('correct_answer', models.ManyToManyField(related_name='correct_answer', to='api.answer', verbose_name='Правильный(е) ответ(ы)')),
                ('options_answer', models.ManyToManyField(blank=True, null=True, related_name='options_answer', to='api.answer', verbose_name='Варианты ответов')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название теста')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание теста')),
                ('tasks', models.ManyToManyField(related_name='tasks', to='api.task', verbose_name='Задания для теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название этапа')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание этапа')),
                ('theory', models.TextField(verbose_name='Теория этапа')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
