# Generated by Django 4.1.5 on 2023-01-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('radio', 'радиобаттоны'), ('checkbox', 'чекбоксы'), ('text', 'текстовый')], default='radio', max_length=50, verbose_name='Тип задания'),
        ),
    ]
